import type { Metadata } from 'next';
import { Libre_Baskerville } from 'next/font/google';
import localFont from 'next/font/local';
import './globals.css';

const libre = Libre_Baskerville({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-libre',
});

const diamondBridge = localFont({
  src: './diamondbridge.otf',
  variable: '--font-diamond',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${libre.variable} ${diamondBridge.variable} font-sans`}>
        {children}
      </body>
    </html>
  );
}
